version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: timetracker-postgres
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: timetracker_user
      POSTGRES_PASSWORD: timetracker_pass
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - timetracker-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: timetracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@timetracker.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - timetracker-network

volumes:
  postgres_data:

networks:
  timetracker-network:
    driver: bridge