version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: timetracker-postgres
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: timetracker_user
      POSTGRES_PASSWORD: timetracker_pass
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
