version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: timetracker-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-timetracker}
      POSTGRES_USER: ${POSTGRES_USER:-timetracker_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-timetracker_pass}
    ports:
      - "${POSTGRES_PORT:-5438}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: