server:
  port: 8081

spring:
  application:
    name: reai-time-tracker-app
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  web:
    resources:
      static-locations:
        - classpath:/static/

reai:
  api:
    base-url: ${REAI_API_BASE_URL}
    validate-endpoint: /api/auth/validate-token
  login:
    url: ${REAI_LOGIN_URL}
  oauth2:
    authorization-endpoint: ${REAI_OAUTH2_AUTH_ENDPOINT}
    token-endpoint: ${REAI_OAUTH2_TOKEN_ENDPOINT}
    redirect-uri: ${REAI_OAUTH2_REDIRECT_URI}

logging:
  level:
    com:
      reai:
        timetracker: ${LOG_LEVEL}
    org:
      springframework:
        web: ${LOG_LEVEL_WEB}

management:
  endpoints:
    web:
      exposure:
        include: health,info
