server:
  port: 8081

spring:
  application:
    name: reai-time-tracker-app
  datasource:
    url: '${DB_URL_PROD:jdbc:postgresql://localhost:5432/timetracker}'
    username: '${DB_USERNAME_PROD:timetracker_user}'
    password: '${DB_PASSWORD_PROD:password}'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  web:
    resources:
      static-locations:
        - classpath:/static/

reai:
  api:
    base-url: '${REAI_API_BASE_URL:http://localhost:8080}'
    validate-endpoint: /api/auth/validate-token
  login:
    url: '${REAI_LOGIN_URL:http://localhost:8080}'
  oauth2:
    authorization-endpoint: '${REAI_OAUTH2_AUTH_ENDPOINT:http://localhost:8080/oauth2/authorize}'
    token-endpoint: '${REAI_OAUTH2_TOKEN_ENDPOINT:http://localhost:8080/oauth2/token}'
    redirect-uri: '${REAI_OAUTH2_REDIRECT_URI:http://localhost:8081}'

logging:
  level:
    com:
      reai:
        timetracker: ${LOG_LEVEL:DEBUG}
    org:
      springframework:
        web: ${LOG_LEVEL_WEB:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: health,info
